import { useEffect, useState } from "react";
import { api, type LiveDemoConfig, type LiveDemoProgress } from "../services/api";

const steps = ["Preflight", "Extract behavior claim", "Prepare sandbox", "Generate focused test", "Check proof integrity", "Validate structured test evidence", "Outcome"];
function outcome(progress: LiveDemoProgress) { return progress.status === "succeeded" ? "Completed outcome" : progress.status === "failed" ? "Operationally inconclusive" : null; }

export function LiveDemo() {
  const [config, setConfig] = useState<LiveDemoConfig>(); const [repository, setRepository] = useState(""); const [issue, setIssue] = useState<number>(); const [acknowledged, setAcknowledged] = useState(false); const [token, setToken] = useState(""); const [progress, setProgress] = useState<LiveDemoProgress>(); const [error, setError] = useState<string>();
  useEffect(() => { api.liveDemoConfig().then((value) => { setConfig(value); setRepository(value.repositories[0] ?? ""); setIssue(value.issue_numbers[0]); }).catch((err: Error) => setError(err.message)); }, []);
  useEffect(() => { if (!progress || progress.terminal) return; const timer = window.setInterval(() => api.liveDemoProgress(progress.id).then(setProgress).catch((err: Error) => setError(err.message)), 1500); return () => window.clearInterval(timer); }, [progress]);
  if (error && !config) return <section className="empty-state"><h1>Live demo unavailable</h1><p>{error}</p></section>;
  if (!config) return <p role="status">Checking live-demo capability…</p>;
  if (!config.enabled) return <section className="empty-state"><p className="eyebrow">Controlled live demo</p><h1>Live demo is disabled for this deployment.</h1>{config.reason !== "Live demo is disabled for this deployment." && <p>{config.reason}</p>}<div className="brief-actions"><a className="button-link" href="?brief=1">Evidence Brief</a><a className="button-link" href="?results=1">Evidence Results</a></div></section>;
  const start = async () => { if (!issue || !repository || !acknowledged) return; setError(undefined); try { const job = await api.startLiveDemo(repository, issue, token || undefined); setProgress({ id: job.id, status: job.status, stage: "queued", detail: "Queued for bounded live investigation", terminal: false, investigation_id: null }); setToken(""); } catch (err) { setError((err as Error).message); } };
  return <section className="live-demo"><p className="eyebrow">Authenticated operator intake</p><h1>Investigate a configured repository issue</h1><p className="results-caveat">This starts a bounded real investigation using configured model and agent resources. It does not post to GitHub.</p><label className="filter-label">Repository <select aria-label="Repository" value={repository} onChange={(event) => setRepository(event.target.value)}>{config.repositories.map((item) => <option key={item} value={item}>{item}</option>)}</select></label>{config.allow_any_issue ? <label className="filter-label">Issue number <input aria-label="Issue number" type="number" min="1" value={issue ?? ""} onChange={(event) => setIssue(Number(event.target.value))} /></label> : <label className="filter-label">Allowlisted issue <select value={issue ?? ""} onChange={(event) => setIssue(Number(event.target.value))}>{config.issue_numbers.map((number) => <option key={number} value={number}>#{number}</option>)}</select></label>}<label className="live-ack"><input type="checkbox" checked={acknowledged} onChange={(event) => setAcknowledged(event.target.checked)} /> I acknowledge this bounded live investigation uses configured resources and does not post to GitHub.</label><label className="filter-label">Operator token (only when configured) <input value={token} type="password" autoComplete="off" onChange={(event) => setToken(event.target.value)} /></label><button className="button-link button-primary" disabled={!issue || !repository || !acknowledged || Boolean(progress && !progress.terminal)} onClick={start}>Start bounded investigation</button>{error && <p className="error" role="alert">{error}</p>}{progress && <section className="card live-progress" aria-live="polite"><h2>{outcome(progress) ?? "Live investigation in progress"}</h2><p>{progress.detail}</p><ol>{steps.map((step) => <li key={step}>{step}</li>)}</ol>{progress.terminal && progress.investigation_id && <a className="button-link" href={`?id=${encodeURIComponent(progress.investigation_id)}`}>Open resulting evidence</a>}</section>}</section>;
}
